/* eslint-disable functional/no-return-void */
import { signIn } from 'masmott/dist/es6/mock';
import Head from 'next/head';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={() => signIn()}>Sign In</button>
      </main>
    </div>
  );
}
