name: Release
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test-app-nextjs-treeshaking-capability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - run: pnpm test-app-nextjs-treeshaking-capability

  test-app-nextjs-treeshaking-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - run: pnpm test-app-nextjs-treeshaking-stack

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - run: pnpm lint

  release:
    needs: [
      lint, 
      test-app-nextjs-treeshaking-capability,
      test-app-nextjs-treeshaking-stack,
    ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        
