name: Release
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run : bash <(curl -sfL https://raw.githubusercontent.com/cachix/install-nix-action/master/install-nix.sh)
        env:
          INPUT_INSTALL_URL:
          INPUT_INSTALL_OPTIONS:
          INPUT_NIX_PATH:
          INPUT_EXTRA_NIX_CONFIG:

      - uses: chimeraant/dev@v1.3.3

      - name: Build es6
        run: pnpm build:es6

      - name: Build cjs
        run: pnpm build:cjs

      - name: Build types
        run: pnpm build:types

      - name: Build cli
        run: pnpm nazna build cli

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release
