name: Release
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test-codegen-app-nextjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - run: pnpm test:codegen-app-nextjs

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - run: pnpm lint

  release:
    needs: [lint, test-codegen-app-nextjs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        
