name: Release
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: chimeraant/dev@v1.3.3

      - run: pnpm build:es6

      - run: pnpm build:cjs

      - run: pnpm build:types

      - run: pnpm lint

      - run: pnpm test:types

      - run: vitest

      - run: pnpm install
        working-directory: e2e/provider/foo

      - run: pnpm build
        working-directory: e2e/provider/foo

      - run: pnpm install
        working-directory: e2e/framework/nextjs

      - run: pnpm generate
        working-directory: e2e/framework/nextjs

      - run: pnpm test:treeshaking
        working-directory: e2e/framework/nextjs

      - run: pnpm test:e2e
        working-directory: e2e/framework/nextjs

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release
