name: Release
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: chimeraant/dev@v1.3.3

      - run: pnpm build:es6

      - run: pnpm build:cjs

      - run: pnpm build:types

      - run: pnpm test:types

      - run: pnpm lint

      - run: pnpm test:codegen-app-nextjs

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release
