name: Release
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Dependencies
        uses: chimeraant/dev@v1.2.66
      - name: Nazna fix
        run: pnpm nazna fix
      - name: Build es6
        run: pnpm build:es6
      - name: Build cjs
        run: pnpm build:cjs
      - name: Build types
        run: pnpm build:types
      - name: Build cli
        run: pnpm nazna build cli
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release
